import type { Metadata } from "next";
import { LOCALES, localizedPath, type Lang, type StaticRoute } from "@/lib/i18n";
import { absoluteUrl } from "@/lib/utils";

/**
 * Link-preview card (WhatsApp, Facebook, Messenger, iMessage, LinkedIn, X…).
 * The brand logo on a 1200x630 white canvas, generated by scripts/make-og-card.mjs
 * and served from public/ — so the Pages sub-path has to be added by hand.
 */
export const OG_IMAGE = {
  url: `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/images/og-logo.jpg`,
  width: 1200,
  height: 630,
  alt: "La Gourmandise des Moches",
} as const;

/** Locale-aware metadata with canonical + hreflang alternates + OG. */
export function pageMetadata(lang: Lang, route: StaticRoute | "", title: string, description: string): Metadata {
  const canonical = absoluteUrl(localizedPath(lang, route));
  const languages = Object.fromEntries([
    ...LOCALES.map((l) => [l, absoluteUrl(localizedPath(l, route))]),
    ["x-default", absoluteUrl(localizedPath("fr", route))],
  ]);
  return {
    title,
    description: description.length > 158 ? `${description.slice(0, 155)}…` : description,
    alternates: { canonical, languages },
    openGraph: {
      title,
      description,
      url: canonical,
      locale: lang === "fr" ? "fr_RE" : "en_US",
      alternateLocale: lang === "fr" ? ["en_US"] : ["fr_RE"],
      images: [{ url: absoluteUrl(OG_IMAGE.url), width: OG_IMAGE.width, height: OG_IMAGE.height, alt: OG_IMAGE.alt }],
    },
    twitter: { card: "summary_large_image", title, description },
  };
}
